-- CreateEnum
CREATE TYPE "EvaluationAssignmentStatus" AS ENUM ('PENDING', 'COMPLETED');

-- AlterTable
ALTER TABLE "Evaluation" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "jobId" TEXT,
ADD COLUMN     "questions" JSONB;

-- CreateTable
CREATE TABLE "EvaluationAssignment" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "evaluationId" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "status" "EvaluationAssignmentStatus" NOT NULL DEFAULT 'PENDING',
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EvaluationAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EvaluationAssignment_token_key" ON "EvaluationAssignment"("token");

-- CreateIndex
CREATE INDEX "EvaluationAssignment_companyId_idx" ON "EvaluationAssignment"("companyId");

-- CreateIndex
CREATE INDEX "EvaluationAssignment_candidateId_idx" ON "EvaluationAssignment"("candidateId");

-- CreateIndex
CREATE INDEX "EvaluationAssignment_token_idx" ON "EvaluationAssignment"("token");

-- AddForeignKey
ALTER TABLE "EvaluationAssignment" ADD CONSTRAINT "EvaluationAssignment_evaluationId_fkey" FOREIGN KEY ("evaluationId") REFERENCES "Evaluation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EvaluationAssignment" ADD CONSTRAINT "EvaluationAssignment_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;
